<?php

function company_theme($existing, $type, $theme, $path) {
  
  return array(
    'companyview' => array(
      'variables' => array('data' => NULL),
    ),
  );
}

function company_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook) {
  if ( $variables['element']['#id'] === 'edit-empidtype') {
    $suggestions[] = $hook . '__config_general';
  }
}

function company_theme_suggestions_form_element_label_alter(array &$suggestions, array $variables, $hook) {
  if ( $variables['element']['#id'] === 'edit-empidtype') {
    $suggestions[] = $hook . '__toggle_label';
  }
}

